project_id = "wlxbydzshqijlfejqafp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
# The default inbucket port is 9000, but we use 54324 to avoid conflicts

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[realtime]
enabled = true

[analytics]
enabled = false

[functions.create-connect-account]
verify_jwt = true

[functions.check-connect-status]
verify_jwt = true

[functions.create-payment-session]
verify_jwt = true

[functions.disconnect-stripe]
verify_jwt = true